[project]
name = "WebServicesManager"
version = "0.1.0"
description = "A template for web services management."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog==6.9.0",
]
